### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by Occhiii623** [Occhiii623/chat-space#10]
# IPアドレス
18.180.204.245

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by Occhiii623** [comment]
問題ないとのことで、ホッといたしました、、、！
確認ありがとうございました！！
